### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by FinderProcess** [yinleiCoder/cs2-cheat-cpp#1]
![111](https://github.com/yinleiCoder/cs2-cheat-cpp/assets/97183873/33991382-da32-4b91-8b0f-3df5f230c8a7)

**Comment by yinleiCoder** [comment]
no，this is cs 2 external cheat sith windows32 api

**Comment by yinleiCoder** [comment]
> ![111](https://private-user-images.githubusercontent.com/97183873/323553774-33991382-da32-4b91-8b0f-3df5f230c8a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzkwODAsIm5iZiI6MTcxMzQzODc4MCwicGF0aCI6Ii85NzE4Mzg3My8zMjM1NTM3NzQtMzM5OTEzODItZGEzMi00YjkxLThiMGYtM2RmNWYyMzBjOGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExMTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDQ0MDZiZGMwMGUyMWI4YWJhYzUwMmVmMmM4ZGYxY2UxYjZjZWRmZmE5ZTcxYTMxOWNlYzU4ZGNiYmY4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dCweMIGmYNDhIyDDV9nJk2kgt2oUoPzMLWkus4W7wHc)

no，this is CS2 external cheat with win32 API
